### PR TITLE
Add blocker div and implement missing VideoJs Tech methods

### PR DESCRIPTION
**Pull request by z4y4ts**
Hi!

We'd like to contribute back our work we've done for https://github.com/raccoongang/xblock-video/

This PR includes two features:

1. Add blocker div element to prevent single click on a video to generate two clicks. This caused video to play&pause or pause&play instead of single action.
2. More complete implementation of VideoJS' Tech interface.
3. Bump version in bower.json. (We install videojs and plugins via bower).

I'm looking forward seeing what you think of this patch.

Best regards,
Alexander

### CODE REVIEW

**Comment by z4y4ts** [comment]
Hi @ryanpatrickcook ,

Hope you're doing well.

Any chance this can be merged into your repo?
How can I help you make this happen?


Best regards,
Alexander

**Comment by davekiss** [comment]
@ryanpatrickcook any thoughts on merging this one?

**Comment by davidtorroija** [comment]
please merge this... we need this code 👍

**Comment by ryanpatrickcook** [comment]
hey guys, yikes. sorry for the delay. ✌️

**Pull request merged**
